Mecanum用のclassを設定した
hs4449889/hairo2021 pull request #42
Opened 2021-10-06 08:54 UTC by hs4449889

# 変更の目的
メカナムホイール用のclassを作成した。

-------------------------------------
# 関連issue
#26 

--------------------------------------

# レビュー完了希望日

### 2021/10/6 (水) 

# After merge
Fix #26 

--------------------------------------

2021-10-06 12:48 UTC, HS-1114G requested changes
メカナムの方向指定と、その他もろもろよろしくお願いします。

2021-10-06 12:48 UTC, HS-1114G commented on Mecanum/mecanum.py
> +    #最終的に辞書を採用(配列は可読性が低い)
辞書あんまりちゃんと知らないから、何とも言えない…
とりあえずめんどくさいことだけは知ってるから、できれば使いたくないな…

2021-10-06 12:48 UTC, HS-1114G commented on Mecanum/mecanum.py
> +        self.specify_motion[,,,]
self.specify_motion = [1, 2, 3, 4]
じゃない？

2021-10-06 12:48 UTC, HS-1114G commented on Controller/ps4.py
> +#TO DO : valueが可変するボタンに対応する
このファイルって、このプルリクで直した奴じゃないよね？？
このファイル更新したら、前みたいにめんどいことになるんじゃない？？

2021-10-06 13:32 UTC, hs4449889 commented on Mecanum/mecanum.py
> +    #最終的に辞書を採用(配列は可読性が低い)
添字じゃなくてkeyでアクセスするから可読性は上がると思ふ

2021-10-06 13:33 UTC, hs4449889 commented on Mecanum/mecanum.py
> +        self.specify_motion[,,,]
値の設定をサボったやつなので、暇なときとかに更新します

2021-10-08 08:08 UTC, HS-1114G requested changes
おそらく下の配列の定義は直さなければいけないと思います。
また、複数のファイルが同時に更新されているようですが大丈夫なのですか？
確認よろしくお願いいたします。

2021-10-08 08:08 UTC, HS-1114G commented on Mecanum/mecanum.py
> +        self.specify_motion = [-1 ,-1 ,-1 ,-1 ]
ここに「＝」ついてるよね？？
※下のコメントの参考

2021-10-08 08:08 UTC, HS-1114G commented on Mecanum/mecanum.py
> +        self.specify_motion[ 0 , 1 , 1 , 0 ]
self.specify_motion = [ 0, 1, 1, 0]
じゃない？
※これ以下すべてを編集した方がいい気がする…

2021-10-08 08:13 UTC, closed without merging